### ISSUE TITLE
疑问 ? 

### ISSUE THREAD

**Issue by rfyiamcool** [XimalayaCloud/xcache#10]
我记得pika以前就加入了codis的支持，另外pika基于rocksdb又封了一层，本就存在mem缓存机制吧，xcache又基于rocksdb又封了层缓存?

**Comment by prcyangli** [comment]
rocksdb的缓存机制是基于sst文件级别的，xcache缓存是基于key级别的更高效，如果命中xcache缓存访问速度会更快，

**Comment by rfyiamcool** [comment]
😁 明白， 这里说的key级别缓存，是含有string list hash zset这类数据结构吧？ 好奇，咱们xcache咱们判断的冷热数据？ 做计数么？

**Comment by prcyangli** [comment]
现在缓存加载策略还比较简单，只要访问不命中就从rocksdb中加载到内存；缓存淘汰策略支持LRU和LFU

**Comment by rfyiamcool** [comment]
谢谢
